### ISSUE TITLE
when fork the front end app, it runs, when i start the back...i get error TS2688:Cannot find type definition file for 'react-dom'

### ISSUE THREAD

**Issue by hmiiro** [arielweinberger/task-management-frontend#1]
when fork the front end app, it runs, when i start the back...i get error TS2688:Cannot find type definition file for 'react-dom'

**Comment by ActoMatics** [comment]
Did you install the type?
npm install @types/node --save-dev
and in tsconfig file add: 
 {
  "compilerOptions": {
    "types": ["node"]
 }
}

**Comment by JoaoVictorDaijo** [comment]
Yeah I get the same error, the solution above didn't work.

Also I get a very big error in the terminal and I'm not sure how to debug this.

<details>
  <summary>Error after running npm run (inside front-end folder)</summary>
  
> nestjs-course-frontend@0.1.0 start /home/electro/Documents/nestjs-task-management/task-management-frontend
> PORT=3001 react-app-rewired start

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-jest": "^24.8.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:

  /home/electro/Documents/nestjs-task-management/node_modules/babel-jest (version: 26.6.3) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /home/electro/Documents/nestjs-task-management/node_modules/babel-jest is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-jest in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-jest.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

P.S. We know this message is long but please read the steps above :-) We hope you find them helpful!

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nestjs-course-frontend@0.1.0 start: `PORT=3001 react-app-rewired start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nestjs-course-frontend@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/electro/.npm/_logs/2021-02-04T22_30_47_800Z-debug.log
  
</details>

<details>
  <summary>COMPLETE LOG</summary>
  
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.18.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle nestjs-course-frontend@0.1.0~prestart: nestjs-course-frontend@0.1.0
6 info lifecycle nestjs-course-frontend@0.1.0~start: nestjs-course-frontend@0.1.0
7 verbose lifecycle nestjs-course-frontend@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle nestjs-course-frontend@0.1.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/electro/Documents/nestjs-task-management/task-management-frontend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle nestjs-course-frontend@0.1.0~start: CWD: /home/electro/Documents/nestjs-task-management/task-management-frontend
10 silly lifecycle nestjs-course-frontend@0.1.0~start: Args: [ '-c', 'PORT=3001 react-app-rewired start' ]
11 silly lifecycle nestjs-course-frontend@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle nestjs-course-frontend@0.1.0~start: Failed to exec start script
13 verbose stack Error: nestjs-course-frontend@0.1.0 start: `PORT=3001 react-app-rewired start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid nestjs-course-frontend@0.1.0
15 verbose cwd /home/electro/Documents/nestjs-task-management/task-management-frontend
16 verbose Linux 5.8.0-41-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v12.18.2
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error nestjs-course-frontend@0.1.0 start: `PORT=3001 react-app-rewired start`
22 error Exit status 1
23 error Failed at the nestjs-course-frontend@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
  
</details>

If I try npm run start:dev from NestJS root folder I get this error:

<details>
  <summary>Spoiler warning</summary>
  
[7:39:26 PM] Starting compilation in watch mode...

task-management-frontend/node_modules/react-scripts/lib/react-app.d.ts:3:23 - error TS2688: Cannot find type definition file for 'react-dom'.

3 /// <reference types="react-dom" />
                        ~~~~~~~~~

[7:39:35 PM] Found 1 error. Watching for file changes.
  
</details>
