### ISSUE TITLE
yarn start  Fail to Complile

### ISSUE THREAD

**Issue by Mohiuddin2** [arielweinberger/task-management-frontend#46]
Failed to compile
./src/index.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/index.scss)
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.12.0
This error occurred during the build time and cannot be dismissed.

**Comment by aaugmentum** [comment]
I got the same error

**Comment by brysbra** [comment]
Make sure that you are using a supported version for node-sass v4.12.0.
See list of supported versions: https://github.com/sass/node-sass/releases/tag/v4.12.0
Then check against your installed version by running `node --version`.

**Comment by sameerrajputra** [comment]
use SKIP_PREFLIGHT_CHECK=true in .env file to bypass errors

**Comment by skoblenick** [comment]
see my comments in #29. updating the versions of node-sass and react-scripts will resolve the issue. i found this as well on a linux machine running the latest LTS.

**Comment by Mrudul-Bhatt** [comment]
Just remove all Sass related files and imports, node-sass has been deprecated. And also remove node-sass package. This will disrupt the styling to some extent but still the front-end will remain good enough to test our API functionalities. You can still fix styling using custom CSS, if you want this front-end and are not creating your own

**Comment by subooom** [comment]
I'm getting `Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Acer\projects\nestjs-task-manager-ui\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\Acer\projects\nestjs-task-manager-ui\node_modules\webpack\lib\NormalModule.js:401:16)
    at C:\Users\Acer\projects\nestjs-task-manager-ui\node_modules\webpack\lib\NormalModule.js:433:10
    at C:\Users\Acer\projects\nestjs-task-manager-ui\node_modules\webpack\lib\NormalModule.js:308:13
    at C:\Users\Acer\projects\nestjs-task-manager-ui\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Acer\projects\nestjs-task-manager-ui\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\Acer\projects\nestjs-task-manager-ui\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\Acer\projects\nestjs-task-manager-ui\node_modules\react-scripts\node_modules\babel-loader\lib\index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}`

**Comment by subooom** [comment]
I ended up removing all `mobx` usage and going with basic `GET`, `POST` requests. I will create a repo for the basic version once I'm done.
